export const LOGGED_IN_USER = "LOGGED_IN_USER";

export const FETCH_STUDENTS_APPLICATION_LIST = "FETCH_STUDENTS_APPLICATION_LIST";
export const FETCH_STUDENTS_APPLICATION_LIST_SUCCESS = "FETCH_STUDENTS_APPLICATION_LIST_SUCCESS";
export const FETCH_STUDENTS_APPLICATION_LIST_ERROR = "FETCH_STUDENTS_APPLICATION_LIST_ERROR";

export const FETCH_COLLEGE_APPLICATION_LIST = "FETCH_COLLEGE_APPLICATION_LIST";
export const FETCH_COLLEGE_APPLICATION_LIST_SUCCESS = "FETCH_COLLEGE_APPLICATION_LIST_SUCCESS";
export const FETCH_COLLEGE_APPLICATION_LIST_ERROR = "FETCH_COLLEGE_APPLICATION_LIST_ERROR";

// export const SET_LOADER = "SET_LOADER";
